name = "beauty"
main = "src/index.ts" # Keeping .ts since you had it in the first block
compatibility_date = "2024-04-01"

[site]
bucket = "./public" 

[[d1_databases]]
binding = "DB"
database_name = "salon-db"
database_id = "46e4eb35-d598-44ba-9f9c-4e629642cdb8"
